server:
  port: ${order-service.port}
spring:
  cloud:
    sentinel:
      transport:
        port: ${sentinel.transport.port.order-service}
        dashboard: ${sentinel.transport.dashboard}
#ssy:
#  username: 松山院
#  site: www.ssy.top